import { defineField, defineType } from 'sanity';

export default defineType({
  name: 'siteSettings',
  title: 'Site Settings',
  type: 'document',
  icon: () => '⚙️',
  fields: [
    defineField({
      name: 'colorTheme',
      title: 'Color Theme',
      type: 'string',
      description: 'Choose a color palette for the website',
      options: {
        list: [
          { title: '🔥 Warm — reds, oranges, golds', value: 'warm' },
          { title: '🌊 Cool — blues, teals, slate', value: 'cool' },
          { title: '🌿 Earth — greens, browns, cream', value: 'earth' },
          { title: '⚡ Bold — deep colors, high contrast', value: 'bold' },
          { title: '🤍 Minimal — black, white, clean', value: 'minimal' },
          { title: '🌙 Dark — dark background, warm accents', value: 'dark' },
          { title: '🍕 Rustic — terracotta & olive (Italian, Pizzeria, Mediterranean)', value: 'rustic' },
          { title: '🌸 Sakura — cherry blossom & indigo (Japanese, Sushi, Asian)', value: 'sakura' },
          { title: '🦞 Ocean — teal & coral (Seafood, Coastal, Hawaiian)', value: 'ocean' },
          { title: '🌶️ Spice — saffron & magenta (Indian, Thai, Middle Eastern)', value: 'spice' },
          { title: '🥂 Bistro — gold & navy (French, Fine Dining, Upscale)', value: 'bistro' },
          { title: '🔥 Smoke — charcoal & amber (BBQ, Steakhouse, American Grill)', value: 'smoke' },
          { title: '🌮 Fiesta — burnt sienna & avocado (Mexican, Tex-Mex, Latin)', value: 'fiesta' },
          { title: '🏮 Lantern — vermilion & gold (Chinese, Dim Sum, Cantonese)', value: 'lantern' },
          { title: '🫒 Olive — sage green & gold (Greek, Mediterranean, Farm-to-table)', value: 'olive' },
          { title: '🍺 Craft — dark amber & malt (Gastropub, Brewery, American)', value: 'craft' },
          { title: '🌺 Tropical — teal & mango (Caribbean, Island, Hawaiian Fusion)', value: 'tropical' },
          { title: '☕ Cafe — espresso & latte (Coffee Shop, Bakery, Brunch)', value: 'cafe' },
          { title: '🌹 Rose — dusty rose & plum (Brunch Spot, Patisserie, Modern European)', value: 'rose' },
          { title: '🎭 Noir — jet black & crimson (Cocktail Bar, Speakeasy, Fine Dining)', value: 'noir' },
        ],
        layout: 'radio',
      },
      initialValue: 'warm',
    }),
    defineField({
      name: 'customColors',
      title: 'Custom Colors',
      type: 'object',
      description: 'Override individual colors on top of the selected theme. Use hex codes like #c2410c. Leave blank to use theme defaults.',
      options: { collapsible: true, collapsed: true },
      fields: [
        defineField({ name: 'primary', title: 'Primary Color', type: 'string', description: 'Main brand color — buttons, highlights. e.g. #c2410c' }),
        defineField({ name: 'primaryDark', title: 'Primary Dark', type: 'string', description: 'Hover/active state of primary. e.g. #9a3412' }),
        defineField({ name: 'accent', title: 'Accent Color', type: 'string', description: 'Secondary accent color. e.g. #d97706' }),
        defineField({ name: 'surface', title: 'Page Background', type: 'string', description: 'Main page background. e.g. #fffbeb' }),
        defineField({ name: 'surfaceAlt', title: 'Section Background', type: 'string', description: 'Alternate section background. e.g. #fef3c7' }),
        defineField({ name: 'textMain', title: 'Main Text Color', type: 'string', description: 'Body text color. e.g. #1c1917' }),
        defineField({ name: 'textMuted', title: 'Muted Text Color', type: 'string', description: 'Secondary/subtle text. e.g. #78716c' }),
        defineField({ name: 'border', title: 'Border Color', type: 'string', description: 'Card borders and dividers. e.g. #e7e5e4' }),
      ],
    }),
    defineField({
      name: 'favicon',
      title: 'Favicon',
      type: 'image',
      description: 'Small icon that appears in the browser tab',
    }),
    defineField({
      name: 'metaTitle',
      title: 'SEO Title',
      type: 'string',
      description: 'Title shown in Google results. If empty, uses restaurant name.',
      validation: (Rule) => Rule.max(60),
    }),
    defineField({
      name: 'metaDescription',
      title: 'SEO Description',
      type: 'text',
      rows: 2,
      description: 'Description shown in Google results. Keep under 160 characters.',
      validation: (Rule) => Rule.max(160),
    }),
    defineField({
      name: 'ogImage',
      title: 'Social Share Image',
      type: 'image',
      description: 'Image shown when your site is shared on Facebook, Twitter, etc.',
    }),
    defineField({
      name: 'showHoursInHero',
      title: 'Show Hours Badge in Hero',
      type: 'boolean',
      description: 'Display "Open until X" or "Opens at X" badge on the homepage hero image',
      initialValue: true,
    }),
  ],
  preview: {
    prepare() {
      return { title: 'Site Settings' };
    },
  },
});
